-- ============================================================================
-- MIGRATION 2: DATA UPSERT AND CONSTRAINTS
-- ============================================================================

-- Insert/Update all plans using the new 'starter' enum value
INSERT INTO public.subscription_plans (id, name, tier, description, price_monthly, price_yearly, price_lifetime, max_boards, max_blocks_per_board, max_messages_per_day, max_api_keys, max_seats, storage_mb, features, is_active, sort_order, plan_type, billing_period, extra_boards)
VALUES ('00000000-0000-0000-0000-000000000001', 'Free', 'free', 'Get started with AI workflows', 0, 0, 0, 3, 10, 50, 2, 1, 100, '["3 boards", "10 blocks per board", "50 messages/day", "100 MB storage", "Community support"]'::jsonb, TRUE, 0, 'subscription', 'monthly', 0)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, description = EXCLUDED.description, price_monthly = EXCLUDED.price_monthly, price_yearly = EXCLUDED.price_yearly, price_lifetime = EXCLUDED.price_lifetime, max_boards = EXCLUDED.max_boards, max_blocks_per_board = EXCLUDED.max_blocks_per_board, max_messages_per_day = EXCLUDED.max_messages_per_day, max_api_keys = EXCLUDED.max_api_keys, max_seats = EXCLUDED.max_seats, storage_mb = EXCLUDED.storage_mb, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, plan_type = EXCLUDED.plan_type, billing_period = EXCLUDED.billing_period, extra_boards = EXCLUDED.extra_boards, updated_at = NOW();

INSERT INTO public.subscription_plans (id, name, tier, description, price_monthly, price_yearly, price_lifetime, max_boards, max_blocks_per_board, max_messages_per_day, max_api_keys, max_seats, storage_mb, features, is_active, sort_order, plan_type, billing_period, checkout_url, extra_boards)
VALUES ('00000000-0000-0000-0000-000000000002', 'Starter Monthly', 'starter', 'For individual creators', 900, 0, 0, 10, 25, 200, 5, 1, 500, '["10 boards", "25 blocks per board", "200 messages/day", "500 MB storage", "Email support"]'::jsonb, TRUE, 1, 'subscription', 'monthly', 'https://polar.sh/checkout/starter-monthly', 0)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, description = EXCLUDED.description, price_monthly = EXCLUDED.price_monthly, price_yearly = EXCLUDED.price_yearly, price_lifetime = EXCLUDED.price_lifetime, max_boards = EXCLUDED.max_boards, max_blocks_per_board = EXCLUDED.max_blocks_per_board, max_messages_per_day = EXCLUDED.max_messages_per_day, max_api_keys = EXCLUDED.max_api_keys, max_seats = EXCLUDED.max_seats, storage_mb = EXCLUDED.storage_mb, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, plan_type = EXCLUDED.plan_type, billing_period = EXCLUDED.billing_period, checkout_url = EXCLUDED.checkout_url, extra_boards = EXCLUDED.extra_boards, updated_at = NOW();

INSERT INTO public.subscription_plans (id, name, tier, description, price_monthly, price_yearly, price_lifetime, max_boards, max_blocks_per_board, max_messages_per_day, max_api_keys, max_seats, storage_mb, features, is_active, sort_order, plan_type, billing_period, checkout_url, extra_boards)
VALUES ('00000000-0000-0000-0000-000000000003', 'Starter Yearly', 'starter', 'For individual creators (save 17%)', 0, 9000, 0, 10, 25, 200, 5, 1, 500, '["10 boards", "25 blocks per board", "200 messages/day", "500 MB storage", "Email support", "2 months free"]'::jsonb, TRUE, 2, 'subscription', 'yearly', 'https://polar.sh/checkout/starter-yearly', 0)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, description = EXCLUDED.description, price_monthly = EXCLUDED.price_monthly, price_yearly = EXCLUDED.price_yearly, price_lifetime = EXCLUDED.price_lifetime, max_boards = EXCLUDED.max_boards, max_blocks_per_board = EXCLUDED.max_blocks_per_board, max_messages_per_day = EXCLUDED.max_messages_per_day, max_api_keys = EXCLUDED.max_api_keys, max_seats = EXCLUDED.max_seats, storage_mb = EXCLUDED.storage_mb, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, plan_type = EXCLUDED.plan_type, billing_period = EXCLUDED.billing_period, checkout_url = EXCLUDED.checkout_url, extra_boards = EXCLUDED.extra_boards, updated_at = NOW();

INSERT INTO public.subscription_plans (id, name, tier, description, price_monthly, price_yearly, price_lifetime, max_boards, max_blocks_per_board, max_messages_per_day, max_api_keys, max_seats, storage_mb, features, is_active, sort_order, plan_type, billing_period, checkout_url, extra_boards)
VALUES ('00000000-0000-0000-0000-000000000004', 'Pro Monthly', 'pro', 'For power users', 1900, 0, 0, -1, 50, 1000, 10, 1, 2048, '["Unlimited boards", "50 blocks per board", "1000 messages/day", "2 GB storage", "Priority support"]'::jsonb, TRUE, 3, 'subscription', 'monthly', 'https://polar.sh/checkout/pro-monthly', 0)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, description = EXCLUDED.description, price_monthly = EXCLUDED.price_monthly, price_yearly = EXCLUDED.price_yearly, price_lifetime = EXCLUDED.price_lifetime, max_boards = EXCLUDED.max_boards, max_blocks_per_board = EXCLUDED.max_blocks_per_board, max_messages_per_day = EXCLUDED.max_messages_per_day, max_api_keys = EXCLUDED.max_api_keys, max_seats = EXCLUDED.max_seats, storage_mb = EXCLUDED.storage_mb, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, plan_type = EXCLUDED.plan_type, billing_period = EXCLUDED.billing_period, checkout_url = EXCLUDED.checkout_url, extra_boards = EXCLUDED.extra_boards, updated_at = NOW();

INSERT INTO public.subscription_plans (id, name, tier, description, price_monthly, price_yearly, price_lifetime, max_boards, max_blocks_per_board, max_messages_per_day, max_api_keys, max_seats, storage_mb, features, is_active, sort_order, plan_type, billing_period, checkout_url, extra_boards)
VALUES ('00000000-0000-0000-0000-000000000005', 'Pro Yearly', 'pro', 'For power users (save 17%)', 0, 19000, 0, -1, 50, 1000, 10, 1, 2048, '["Unlimited boards", "50 blocks per board", "1000 messages/day", "2 GB storage", "Priority support", "2 months free"]'::jsonb, TRUE, 4, 'subscription', 'yearly', 'https://polar.sh/checkout/pro-yearly', 0)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, description = EXCLUDED.description, price_monthly = EXCLUDED.price_monthly, price_yearly = EXCLUDED.price_yearly, price_lifetime = EXCLUDED.price_lifetime, max_boards = EXCLUDED.max_boards, max_blocks_per_board = EXCLUDED.max_blocks_per_board, max_messages_per_day = EXCLUDED.max_messages_per_day, max_api_keys = EXCLUDED.max_api_keys, max_seats = EXCLUDED.max_seats, storage_mb = EXCLUDED.storage_mb, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, plan_type = EXCLUDED.plan_type, billing_period = EXCLUDED.billing_period, checkout_url = EXCLUDED.checkout_url, extra_boards = EXCLUDED.extra_boards, updated_at = NOW();

INSERT INTO public.subscription_plans (id, name, tier, description, price_monthly, price_yearly, price_lifetime, max_boards, max_blocks_per_board, max_messages_per_day, max_api_keys, max_seats, storage_mb, features, is_active, sort_order, plan_type, billing_period, checkout_url, extra_boards)
VALUES ('00000000-0000-0000-0000-000000000006', 'Team Monthly', 'team', 'For teams and organizations', 4900, 0, 0, -1, -1, -1, -1, 10, 10240, '["Unlimited everything", "10 team seats", "10 GB storage", "Dedicated support", "SSO (coming soon)"]'::jsonb, TRUE, 5, 'subscription', 'monthly', 'https://polar.sh/checkout/team-monthly', 0)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, description = EXCLUDED.description, price_monthly = EXCLUDED.price_monthly, price_yearly = EXCLUDED.price_yearly, price_lifetime = EXCLUDED.price_lifetime, max_boards = EXCLUDED.max_boards, max_blocks_per_board = EXCLUDED.max_blocks_per_board, max_messages_per_day = EXCLUDED.max_messages_per_day, max_api_keys = EXCLUDED.max_api_keys, max_seats = EXCLUDED.max_seats, storage_mb = EXCLUDED.storage_mb, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, plan_type = EXCLUDED.plan_type, billing_period = EXCLUDED.billing_period, checkout_url = EXCLUDED.checkout_url, extra_boards = EXCLUDED.extra_boards, updated_at = NOW();

INSERT INTO public.subscription_plans (id, name, tier, description, price_monthly, price_yearly, price_lifetime, max_boards, max_blocks_per_board, max_messages_per_day, max_api_keys, max_seats, storage_mb, features, is_active, sort_order, plan_type, billing_period, checkout_url, extra_boards)
VALUES ('00000000-0000-0000-0000-000000000007', 'Team Yearly', 'team', 'For teams (save 17%)', 0, 49000, 0, -1, -1, -1, -1, 10, 10240, '["Unlimited everything", "10 team seats", "10 GB storage", "Dedicated support", "SSO (coming soon)", "2 months free"]'::jsonb, TRUE, 6, 'subscription', 'yearly', 'https://polar.sh/checkout/team-yearly', 0)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, description = EXCLUDED.description, price_monthly = EXCLUDED.price_monthly, price_yearly = EXCLUDED.price_yearly, price_lifetime = EXCLUDED.price_lifetime, max_boards = EXCLUDED.max_boards, max_blocks_per_board = EXCLUDED.max_blocks_per_board, max_messages_per_day = EXCLUDED.max_messages_per_day, max_api_keys = EXCLUDED.max_api_keys, max_seats = EXCLUDED.max_seats, storage_mb = EXCLUDED.storage_mb, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, plan_type = EXCLUDED.plan_type, billing_period = EXCLUDED.billing_period, checkout_url = EXCLUDED.checkout_url, extra_boards = EXCLUDED.extra_boards, updated_at = NOW();

INSERT INTO public.subscription_plans (id, name, tier, description, price_monthly, price_yearly, price_lifetime, max_boards, max_blocks_per_board, max_messages_per_day, max_api_keys, max_seats, storage_mb, features, is_active, sort_order, plan_type, billing_period, checkout_url, is_lifetime, extra_boards)
VALUES ('00000000-0000-0000-0000-000000000008', 'Pro Lifetime', 'pro', 'One-time purchase, forever access', 0, 0, 39900, -1, 50, 1000, 10, 1, 2048, '["Unlimited boards", "50 blocks per board", "1000 messages/day", "2 GB storage", "Priority support", "Lifetime access"]'::jsonb, TRUE, 7, 'subscription', 'lifetime', 'https://polar.sh/checkout/pro-lifetime', TRUE, 0)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, description = EXCLUDED.description, price_monthly = EXCLUDED.price_monthly, price_yearly = EXCLUDED.price_yearly, price_lifetime = EXCLUDED.price_lifetime, max_boards = EXCLUDED.max_boards, max_blocks_per_board = EXCLUDED.max_blocks_per_board, max_messages_per_day = EXCLUDED.max_messages_per_day, max_api_keys = EXCLUDED.max_api_keys, max_seats = EXCLUDED.max_seats, storage_mb = EXCLUDED.storage_mb, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, plan_type = EXCLUDED.plan_type, billing_period = EXCLUDED.billing_period, checkout_url = EXCLUDED.checkout_url, is_lifetime = EXCLUDED.is_lifetime, extra_boards = EXCLUDED.extra_boards, updated_at = NOW();

-- Add-ons
INSERT INTO public.subscription_plans (id, name, tier, description, price_monthly, price_yearly, price_lifetime, max_boards, max_blocks_per_board, max_messages_per_day, max_api_keys, max_seats, storage_mb, features, is_active, sort_order, plan_type, billing_period, checkout_url, extra_boards)
VALUES 
('00000000-0000-0000-0000-000000000101', '+5 Boards', NULL, 'Add 5 extra boards', 0, 0, 499, 0, 0, 0, 0, 0, 0, '["+5 boards", "One-time purchase"]'::jsonb, TRUE, 100, 'addon', 'one_time', 'https://polar.sh/checkout/addon-5-boards', 5),
('00000000-0000-0000-0000-000000000102', '+10 Boards', NULL, 'Add 10 extra boards', 0, 0, 899, 0, 0, 0, 0, 0, 0, '["+10 boards", "One-time purchase"]'::jsonb, TRUE, 101, 'addon', 'one_time', 'https://polar.sh/checkout/addon-10-boards', 10),
('00000000-0000-0000-0000-000000000103', '+500MB Storage', NULL, 'Add 500MB storage', 0, 0, 299, 0, 0, 0, 0, 0, 500, '["+500MB storage", "One-time purchase"]'::jsonb, TRUE, 102, 'addon', 'one_time', 'https://polar.sh/checkout/addon-500mb-storage', 0),
('00000000-0000-0000-0000-000000000104', '+2GB Storage', NULL, 'Add 2GB storage', 0, 0, 999, 0, 0, 0, 0, 0, 2048, '["+2GB storage", "One-time purchase"]'::jsonb, TRUE, 103, 'addon', 'one_time', 'https://polar.sh/checkout/addon-2gb-storage', 0),
('00000000-0000-0000-0000-000000000105', '+5GB Storage', NULL, 'Add 5GB storage', 0, 0, 1999, 0, 0, 0, 0, 0, 5120, '["+5GB storage", "One-time purchase"]'::jsonb, TRUE, 104, 'addon', 'one_time', 'https://polar.sh/checkout/addon-5gb-storage', 0)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, description = EXCLUDED.description, price_monthly = EXCLUDED.price_monthly, price_yearly = EXCLUDED.price_yearly, price_lifetime = EXCLUDED.price_lifetime, max_boards = EXCLUDED.max_boards, max_blocks_per_board = EXCLUDED.max_blocks_per_board, max_messages_per_day = EXCLUDED.max_messages_per_day, max_api_keys = EXCLUDED.max_api_keys, max_seats = EXCLUDED.max_seats, storage_mb = EXCLUDED.storage_mb, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, plan_type = EXCLUDED.plan_type, billing_period = EXCLUDED.billing_period, checkout_url = EXCLUDED.checkout_url, extra_boards = EXCLUDED.extra_boards, updated_at = NOW();

-- Migrate existing subscriptions to new plan IDs
UPDATE public.user_subscriptions SET plan_id = '00000000-0000-0000-0000-000000000001' WHERE plan_id IN (SELECT id FROM public.subscription_plans WHERE tier = 'free' AND id != '00000000-0000-0000-0000-000000000001');
UPDATE public.user_subscriptions SET plan_id = '00000000-0000-0000-0000-000000000004' WHERE plan_id IN (SELECT id FROM public.subscription_plans WHERE tier = 'pro' AND id NOT IN ('00000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000005', '00000000-0000-0000-0000-000000000008'));
UPDATE public.user_subscriptions SET plan_id = '00000000-0000-0000-0000-000000000006' WHERE plan_id IN (SELECT id FROM public.subscription_plans WHERE tier = 'team' AND id NOT IN ('00000000-0000-0000-0000-000000000006', '00000000-0000-0000-0000-000000000007'));
UPDATE public.user_subscriptions SET plan_id = '00000000-0000-0000-0000-000000000006' WHERE plan_id IN (SELECT id FROM public.subscription_plans WHERE tier = 'enterprise');

-- Delete old plans
DELETE FROM public.subscription_plans WHERE id NOT IN ('00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000003','00000000-0000-0000-0000-000000000004','00000000-0000-0000-0000-000000000005','00000000-0000-0000-0000-000000000006','00000000-0000-0000-0000-000000000007','00000000-0000-0000-0000-000000000008','00000000-0000-0000-0000-000000000101','00000000-0000-0000-0000-000000000102','00000000-0000-0000-0000-000000000103','00000000-0000-0000-0000-000000000104','00000000-0000-0000-0000-000000000105');

-- Add constraints
ALTER TABLE public.subscription_plans DROP CONSTRAINT IF EXISTS chk_plan_type_valid;
ALTER TABLE public.subscription_plans DROP CONSTRAINT IF EXISTS chk_tier_consistency;
ALTER TABLE public.subscription_plans DROP CONSTRAINT IF EXISTS chk_addon_limits_only;
ALTER TABLE public.subscription_plans DROP CONSTRAINT IF EXISTS chk_subscription_has_price;
ALTER TABLE public.subscription_plans DROP CONSTRAINT IF EXISTS chk_addon_has_onetime_price;

ALTER TABLE public.subscription_plans ADD CONSTRAINT chk_plan_type_valid CHECK (plan_type IN ('subscription', 'addon'));
ALTER TABLE public.subscription_plans ADD CONSTRAINT chk_tier_consistency CHECK ((plan_type = 'addon' AND tier IS NULL) OR (plan_type = 'subscription' AND tier IS NOT NULL));
ALTER TABLE public.subscription_plans ADD CONSTRAINT chk_addon_limits_only CHECK (plan_type = 'subscription' OR (plan_type = 'addon' AND max_boards = 0 AND max_blocks_per_board = 0 AND max_messages_per_day = 0 AND max_api_keys = 0 AND max_seats = 0));
ALTER TABLE public.subscription_plans ADD CONSTRAINT chk_subscription_has_price CHECK (plan_type = 'addon' OR (plan_type = 'subscription' AND (price_monthly > 0 OR price_yearly > 0 OR price_lifetime > 0 OR tier = 'free')));
ALTER TABLE public.subscription_plans ADD CONSTRAINT chk_addon_has_onetime_price CHECK (plan_type = 'subscription' OR (plan_type = 'addon' AND price_lifetime > 0 AND price_monthly = 0 AND price_yearly = 0));

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_subscription_plans_plan_type ON public.subscription_plans(plan_type);
CREATE INDEX IF NOT EXISTS idx_subscription_plans_tier ON public.subscription_plans(tier) WHERE tier IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_subscription_plans_active ON public.subscription_plans(is_active) WHERE is_active = TRUE;

-- Comments
COMMENT ON TABLE public.user_addons IS 'Tracks purchased add-ons. Stackable.';
COMMENT ON COLUMN public.subscription_plans.plan_type IS 'subscription or addon';
COMMENT ON COLUMN public.subscription_plans.extra_boards IS 'Additional boards for add-ons (stacks with base plan)';
COMMENT ON COLUMN public.subscription_plans.storage_mb IS 'Storage limit in MB (-1 = unlimited)';
COMMENT ON COLUMN public.subscription_plans.price_lifetime IS 'One-time price for lifetime/add-on purchases (cents)';
COMMENT ON COLUMN public.user_subscriptions.grace_status IS 'Tracks if user exceeds limits after downgrade';
COMMENT ON COLUMN public.user_subscriptions.snapshot_max_boards IS 'Plan limits at time of purchase (audit trail)';
COMMENT ON FUNCTION public.get_user_effective_limits IS 'Returns combined limits. -1 = unlimited. Falls back to Free plan.';
COMMENT ON FUNCTION public.get_user_subscription IS 'Returns subscription with effective limits. Guarantees a row - falls back to Free.';
COMMENT ON FUNCTION public.update_user_grace_status IS 'Called after plan changes to detect and set grace period if user exceeds new limits.';